# Generated by Django 3.1.7 on 2021-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addminutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('attendees_name', models.TextField()),
                ('talking_points', models.TextField()),
                ('action_items', models.TextField()),
            ],
            options={
                'db_table': 'minutesDB',
            },
        ),
        migrations.CreateModel(
            name='attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('attendance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'attendeesDB',
            },
        ),
        migrations.CreateModel(
            name='createMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
            options={
                'db_table': 'meetingDB',
            },
        ),
    ]
